info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local

logging:
    level:
        no.skatteetaten.aurora.brio: DEBUG
        ske.aurora: INFO
        no.skatteetaten: INFO
        org:
            springframework: INFO
            apache.catalina: WARN
            hibernate: WARN

integrations:
    cmdb:
        url: "https://cmdb.sits.no/auto/schema/141"
        accessToken: "QI3KkOnWSvn55I3gODMkoKnlA3m9OW5X"
---
spring:
    profiles: local


management:
    server.port: 8081


logging:
    pattern:
        console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"